export function crawlReportMarkdown(comparison) {
  const rows = comparison.primaryCases
    .map(
      (item, index) =>
        `| ${index + 1} | ${escapeCell(new URL(item.requestedUrl).pathname)} | ${item.classification} | ${escapeCell(item.reason ?? item.differences?.join(", ") ?? "")} |`,
    )
    .join("\n");
  const controls = comparison.negativeControls
    .map(
      (item) =>
        `| ${item.id} | ${item.expectedSurface} | ${item.classification} |`,
    )
    .join("\n");
  const counts = Object.entries(comparison.counts)
    .map(([name, count]) => `- ${name}: ${count}`)
    .join("\n");
  return `# Crawling compatibility proof

Protocol: \`${comparison.protocol}\`

This report compares observable crawl outcomes. It does not claim that Stasis
retains Crawlee's RequestQueue/Dataset implementation, and it makes no speed
claim because Playwright pages and fresh Stasis processes are different
execution units.

## Primary result

- Frozen denominator: ${comparison.primaryDenominator} pages
- Baseline valid: ${comparison.baselineValid}
- Candidate artifact valid: ${comparison.candidateValid}
- Exact equivalent rate: ${(comparison.exactEquivalentRate * 100).toFixed(1)}%
- Supported/equivalent-or-disclosed rate: ${(comparison.behaviorallySupportedRate * 100).toFixed(1)}%
- Scheduled URL-set Jaccard: ${comparison.scheduledUrlJaccard.toFixed(4)}
${counts}

| # | Requested path | Classification | Detail |
| ---: | --- | --- | --- |
${rows}

## Declared negative controls

| Case | Expected surface | Classification |
| --- | --- | --- |
${controls}

## Performance boundary

Raw wall times are retained only as diagnostics. No comparative performance
claim is generated by this protocol.
`;
}

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}
